server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册到eurekaserver的 默认true
    fetch-registry: true #是否从eurekaserver抓取已有的注册信息 默认true 单节点无所谓 集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群

#  EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE
#  UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD
#  AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.

# EUREKA自我保护机制