server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    #采样率值介于 0 到 1 之间，1 则表示全部采集
    probability: 1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?usrUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456



mybatis:
  type-aliases-package: com.springcloud.entity #所有Entity别名类所在包
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册到eurekaserver的 默认true
    fetch-registry: true #是否从eurekaserver抓取已有的注册信息 默认true 单节点无所谓 集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka  #单机版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群



  instance:
    instance-id: payment8001 #更改主机名
    prefer-ip-address: true #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 1 #eureka客户端向服务端发送心跳的时间间隔 单位为秒 默认30s
    lease-expiration-duration-in-seconds: 2 #eureka服务端在收到最后一次心跳后等待的时间上限 单位为s 默认90s 超时将剔除服务